image: golang:1.17

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

compile-job:
  stage: build
  script:
  - go build
  rules:
    - when: always

lint-job:
  image: golangci/golangci-lint:v1.45
  rules:
    - if: $CI_COMMIT_BRANCH !~ "dev|main"
      when: never
    - if: $CI_COMMIT_BRANCH =~ "dev|main"
  stage: test
  script:
    # Use default .golangci.yml file from the image if one is not present in the project root.
    #- '[ -e .golangci.yml ] || cp /golangci/.golangci.yml .'
    # Write the code coverage report to gl-code-quality-report.json
    # and print linting issues to stdout in the format: path/to/file:line description
    # remove `--issues-exit-code 0` or set to non-zero to fail the job if linting issues are detected
    # ./lint.sh
    - golangci-lint run
  allow_failure: true

test-job:
  rules:
    - if: $CI_COMMIT_BRANCH !~ "dev|main"
      when: never
    - if: $CI_COMMIT_BRANCH =~ "dev|main"
  stage: test
  script:
  - go test ./... -coverprofile=cov.out -v
  - go tool cover -html=cov.out -o cov.html
  - go tool cover -func=cov.out
  artifacts:
    paths:
      - cov.html
    expire_in: 30 days
  coverage: "/\\(statements\\)\\s+\\d+.?\\d+%/"

pages:
  stage: deploy
  script:
    - rm -f public/cov.html
    - mkdir -p public
    - cp cov.html public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - main
    - dev


